# -*- coding: utf-8 -*-
"""exp_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/131jeqTPD4UkYHFXfdLnL1_nVgt0Kg_ak
"""

# ============================================================
# ShiftWise Experiments — только shift_mode (с WandB)
# ============================================================

# 1. Установка и импорты
!pip install wandb -q

import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import wandb

print("="*60)
print("ShiftWise Experiments — shift_mode (с WandB)")
print("="*60)

# 2. Проверка GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")
if device.type == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)}")
print()

# 3. WandB авторизация
wandb.login()
print("✓ WandB авторизован")

# 4. ЗАГЛУШКА SHIFTADD
class ShiftAddConv(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=3,
                 stride=1, padding=1, groups=1, bias=False,
                 sparse_gap=1, num_paths=4, shift_mode='diagonal', **kwargs):
        super().__init__()

        self.sparse_gap = max(1, sparse_gap)
        pad = kernel_size // 2 if isinstance(kernel_size, int) else kernel_size[0] // 2

        self.main_conv = nn.Conv2d(in_channels, out_channels, kernel_size,
                                   stride=stride, padding=pad, groups=groups, bias=bias)

        gap = self.sparse_gap
        if shift_mode == 'diagonal':
            self.shifts = [(gap, gap), (-gap, -gap), (gap, -gap), (-gap, gap)]
        elif shift_mode == 'cross':
            self.shifts = [(gap, 0), (-gap, 0), (0, gap), (0, -gap)]
        else:
            self.shifts = [(gap, gap), (-gap, -gap), (gap, -gap), (-gap, gap),
                          (gap, 0), (-gap, 0), (0, gap), (0, -gap)]
        self.shifts = self.shifts[:num_paths]

        self.shift_convs = nn.ModuleList([
            nn.Conv2d(in_channels, out_channels, kernel_size,
                      stride=stride, padding=pad, groups=groups, bias=False)
            for _ in self.shifts
        ])

        nn.init.kaiming_normal_(self.main_conv.weight, mode='fan_out')
        for sc in self.shift_convs:
            nn.init.kaiming_normal_(sc.weight, mode='fan_out')
            sc.weight.data.mul_(0.1)

    def forward(self, x):
        out = self.main_conv(x)
        for i, (sh, sw) in enumerate(self.shifts):
            shifted = torch.roll(x, shifts=(sh, sw), dims=(2, 3))
            out = out + self.shift_convs[i](shifted) * 0.3
        return out

print("✓ ShiftAddConv загружен")

# 5. МОДЕЛЬ
class LayerNorm2d(nn.Module):
    def __init__(self, dim, eps=1e-6):
        super().__init__()
        self.norm = nn.LayerNorm(dim, eps=eps)
    def forward(self, x):
        return self.norm(x.permute(0, 2, 3, 1)).permute(0, 3, 1, 2)

class ShiftWiseBlock(nn.Module):
    def __init__(self, dim, sparse_gap=3, num_paths=4, shift_mode='diagonal', expand=4):
        super().__init__()
        self.dw = ShiftAddConv(dim, dim, 3, padding=1, groups=dim, bias=False,
                               sparse_gap=sparse_gap, num_paths=num_paths, shift_mode=shift_mode)
        self.norm = LayerNorm2d(dim)
        self.pw1 = nn.Conv2d(dim, dim * expand, 1)
        self.act = nn.GELU()
        self.pw2 = nn.Conv2d(dim * expand, dim, 1)
        self.gamma = nn.Parameter(1e-6 * torch.ones(dim, 1, 1))
    def forward(self, x):
        return x + self.gamma * self.pw2(self.act(self.pw1(self.norm(self.dw(x)))))

class ShiftWiseCIFAR(nn.Module):
    DIMS = [64, 128, 256, 512]
    DEPTHS = [2, 2, 6, 2]

    def __init__(self, num_classes=100, sparse_gap=3, num_paths=4, shift_mode='diagonal'):
        super().__init__()
        self.stem = nn.Sequential(
            nn.Conv2d(3, self.DIMS[0], 3, padding=1, bias=False),
            LayerNorm2d(self.DIMS[0]),
        )
        self.stages = nn.ModuleList()
        for i, (dim, depth) in enumerate(zip(self.DIMS, self.DEPTHS)):
            layers = []
            if i > 0:
                layers += [nn.Conv2d(self.DIMS[i-1], dim, 2, stride=2, bias=False), LayerNorm2d(dim)]
            for _ in range(depth):
                layers += [ShiftWiseBlock(dim, sparse_gap, num_paths, shift_mode)]
            self.stages.append(nn.Sequential(*layers))
        self.norm = LayerNorm2d(self.DIMS[-1])
        self.head = nn.Sequential(nn.AdaptiveAvgPool2d(1), nn.Flatten(), nn.Linear(self.DIMS[-1], num_classes))

    def forward(self, x):
        x = self.stem(x)
        for stage in self.stages:
            x = stage(x)
        return self.head(self.norm(x))

print("✓ Модель создана")

# 6. ДАННЫЕ
transform_train = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.5071, 0.4867, 0.4408), (0.2675, 0.2565, 0.2761)),
])
transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5071, 0.4867, 0.4408), (0.2675, 0.2565, 0.2761)),
])

print("Загрузка CIFAR-100...")
train_set = torchvision.datasets.CIFAR100(root='./data', train=True, download=True, transform=transform_train)
test_set = torchvision.datasets.CIFAR100(root='./data', train=False, download=True, transform=transform_test)

train_loader = DataLoader(train_set, batch_size=128, shuffle=True, num_workers=2)
test_loader = DataLoader(test_set, batch_size=128, shuffle=False, num_workers=2)

print(f"Train: {len(train_set)} images, Test: {len(test_set)} images")
print()

# 7. ФУНКЦИИ ОБУЧЕНИЯ
def train_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss = 0
    correct = 0
    total = 0
    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()
    return total_loss / len(loader), 100. * correct / total

def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss = 0
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)
            total_loss += loss.item()
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()
    return total_loss / len(loader), 100. * correct / total

# 8. ЭКСПЕРИМЕНТ: SHIFT_MODE
print("="*60)
print("ЭКСПЕРИМЕНТ: Влияние shift_mode (с WandB)")
print("="*60)

shift_modes = ['diagonal', 'cross', 'full']
results_mode = {}

for mode in shift_modes:
    print(f"\n▶ Training with shift_mode={mode}")

    wandb.init(
        project="shiftwise-cifar100",
        name=f"shift_mode_{mode}",
        config={
            "experiment": "shift_mode",
            "sparse_gap": 3,
            "num_paths": 4,
            "shift_mode": mode,
            "epochs": 20,
            "batch_size": 128,
            "learning_rate": 3e-3,
            "dataset": "CIFAR-100"
        }
    )

    model = ShiftWiseCIFAR(num_classes=100, sparse_gap=3, num_paths=4, shift_mode=mode).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=3e-3, weight_decay=0.05)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=20)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(20):
        train_loss, train_acc = train_epoch(model, train_loader, optimizer, criterion, device)
        test_loss, test_acc = evaluate(model, test_loader, criterion, device)
        scheduler.step()

        wandb.log({
            "epoch": epoch + 1,
            "train_loss": train_loss,
            "train_acc": train_acc,
            "test_loss": test_loss,
            "test_acc": test_acc,
            "lr": optimizer.param_groups[0]['lr']
        })

        if (epoch + 1) % 10 == 0:
            print(f"  Epoch {epoch+1}/20: Train Acc={train_acc:.2f}%, Test Acc={test_acc:.2f}%")

    results_mode[mode] = test_acc
    print(f"  ✓ shift_mode={mode}: final test accuracy = {test_acc:.2f}%")
    wandb.finish()

print("\n" + "-"*40)
print("Результаты Experiment: shift_mode")
for mode, acc in results_mode.items():
    print(f"  mode={mode:>8}: {acc:.2f}%")
print("-"*40)

print("\n Все эксперименты завершены!")
print(" WandB: https://wandb.ai/fazilov2321-higher-school-of-economics/shiftwise-cifar100")